language: go

go:
    - 1.5.1
    - tip
os:
    - linux
    - osx
    - windows

env:
    - GO15VENDOREXPERIMENT="1"

script: 
    - go build ./client ./server ./utils ./conn 
    - go build -o ./examples/server ./examples/server.go
    - go build -o ./examples/client ./examples/client.go
    - go test ./client ./server ./utils ./conn
